stages:
  - gen-docs

gen-yurucan-docs:
  image: python:latest
  stage: gen-docs
  rules:
    # only run this job if this directory content changes
    - changes:
      - flask/jinja/template.html
      - flask/jinja/gen-docs.py
      - flask/jinja/gitlabci.yml
      when: always
    - when: never

  before_script:
    - pip3 install jinja2 pyyaml

  script:
    - cd flask/jinja
    - python3 gen-docs.py

  artifacts:
    paths:
      - flask/jinja/output/output.html
