stages:
  - gen-docs

gen-yurucan-docs:
  image: python:latest
  stage: gen-docs
  rules:
    # only run this job if this directory content changes
    - changes:
      - template.html
      - gen-docs.py
      - gitlabci.yml
      when: always
    - when: never

  before_script:
    - pip3 install jinja2 pyyaml

  script:
    - cd docs
    - python3 gen-docs.py

  artifacts:
    paths:
      - docs/output/output.html
