# Top-level gitlab CI file
# Should only include project-specific file
# and the project-specific files should be configured to only run jobs if their own files are changed.

stages:
  - docker-build
  - c-build
  - c-test

include:
  - local: '/docker/basics/gitlabci.yml'
  - local: '/gnu/gnu-hello/gitlabci.yml'
