# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  #
  id_rsa_pub = File.read("#{Dir.home}/.ssh/id_rsa.pub")
  config.vm.provision "copy ssh public key", type: "shell",
    inline: "echo \"#{id_rsa_pub}\" >> /home/vagrant/.ssh/authorized_keys"

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.define "bastion1", primary:true do |bast1|
    bast1.vm.box = "generic/ubuntu2004"

    bast1.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
      end

    bast1.vm.network "private_network", ip: "10.1.1.20"
    bast1.vm.hostname = "bastion1"

    username = "regularbloke"

    bast1.vm.provision "shell", inline: <<-SHELL
      sudo adduser --disabled-password --gecos "" #{username}
      mkdir -v -p /home/#{username}/.ssh/
      echo \"#{id_rsa_pub}\" >> /home/#{username}/.ssh/authorized_keys
      chmod -v 644 /home/#{username}/.ssh/authorized_keys
      chmod -v -R 700 /home/#{username}/.ssh
      chown -R #{username}:#{username} /home/#{username}/.ssh
    SHELL
  end

  # boxes at https://vagrantcloud.com/search.
  config.vm.define "bastion2" do |bast2|
    bast2.vm.box = "generic/ubuntu2004"

    bast2.vm.provider "virtualbox" do |vb2|
      vb2.memory = 512
      vb2.cpus = 1
      end

    bast2.vm.network "private_network", ip: "10.1.1.25"
    bast2.vm.hostname = "bastion2"

    username = "importantbloke"

    bast2.vm.provision "shell", inline: <<-SHELL
      sudo adduser --disabled-password --gecos "" #{username}
      mkdir -v -p /home/#{username}/.ssh/
      echo \"#{id_rsa_pub}\" >> /home/#{username}/.ssh/authorized_keys
      chmod -v 644 /home/#{username}/.ssh/authorized_keys
      chmod -v -R 700 /home/#{username}/.ssh
      chown -R #{username}:#{username} /home/#{username}/.ssh
    SHELL
  end

  config.vm.define "appserver" do |app|
    app.vm.box = "generic/ubuntu2004"

    app.vm.provider "virtualbox" do |vb3|
      vb3.memory = 2048
      vb3.cpus = 2
      end

    app.vm.network "private_network", ip: "10.1.1.30"
    app.vm.hostname = "appserver"

    username = "bigwig"

    app.vm.provision "shell", inline: <<-SHELL
      sudo adduser --disabled-password --gecos "" #{username}
      mkdir -v -p /home/#{username}/.ssh/
      echo \"#{id_rsa_pub}\" >> /home/#{username}/.ssh/authorized_keys
      chmod -v 644 /home/#{username}/.ssh/authorized_keys
      chmod -v -R 700 /home/#{username}/.ssh
      chown -R #{username}:#{username} /home/#{username}/.ssh
    SHELL
  end


  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
