# Based on examples in https://github.com/hashicorp/vagrant/issues/3799

Vagrant.configure("2") do |config|
  config.vm.define "machine" do |v|
    v.vm.provider "docker" do |d|
      # Base of this existing image
      #d.image = "phusion/baseimage"
      # or build from a dockerfile directly
      d.build_dir = "."
      d.cmd = ["/sbin/my_init", "--enable-insecure-key"]
      d.name = "dockerizedvm"
      d.has_ssh = true
    end
    v.ssh.port = 2222
    v.ssh.username = 'root'
    v.ssh.private_key_path = 'insecure_key'
    #v.vm.provision "shell", inline: "echo hello"
    #v.vm.synced_folder "./keys", "/vagrant"
  end
end
